/* Microchip Technology Inc. and its subsidiaries.  You may use this software
 * and any derivatives exclusively with Microchip products.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
 * TERMS.
 */

/* Microchip Technology Inc. e suas subsidiАrias.
 * VocЙ pode usar este software e quaisquer derivados
 * exclusivamente com produtos Microchip.

 * ESTE SOFTWARE и FORNECIDO PELA MICROCHIP "TAL COMO ESTа".
 * NENHUMA GARANTIA, EXPRESSA, IMPLмCITA OU ESTATUTаRIA,
 * SE APLICA A ESTE SOFTWARE, INCLUINDO QUALQUER GARANTIA IMPLмCITA
 * DE NцO INFRACгцO, COMERCIALIZAгцO E ADEQUAгцO A UM PROPсSITO ESPECмFICO OU
 * SUA INTERAгцO COM PRODUTOS MICROCHIP,
 * COMBINAгцO COM QUALQUER OUTRO PRODUTO OU UTILIZAгцO EM QUALQUER APLICAгцO.
 *
 * EM NENHUM CASO A MICROCHIP SERа RESPONSаVEL POR QUALQUER PERDA INDIRETO,
 * ESPECIAL, PUNITIVA, INCIDENTAL OU CONSEQUENCIAL,DANOS, CUSTO OU
 * DESPESAS DE QUALQUER TIPO DE RELAгцO COM O SOFTWARE, NO ENTANTO, CAUSADO,
 * MESMO QUE MICROCHIP TENHA SIDO AVISADA DA POSSIBILIDADE OU
 * DOS DANOS PREVISмVEIS.
 * NA MаXIMA EXTENSцO PERMITIDA POR LEI,A RESPONSABILIDADE TOTAL DA MICROCHIP
 * EM TODAS AS REIVINDICAгуES DE QUALQUER FORMA RELATIVA A ESTE SOFTWARE
 * NцO EXCEDERа A QUANTIDADE DE TAXAS, SE HOUVER,
 * QUE VOCй PAGOU DIRETAMENTE ю MICROCHIP POR ESTE SOFTWARE.
 *
 * A MICROCHIP FORNECE ESTE SOFTWARE CONDICIONALMENTE COM SUA ACEITAгцO
 * DESTES TERMOS.
═*/

/*
 * File:    config.h
 * Author:  José W R Pereira
 * Comments:Arquivo de configuraГЦo do microcontrolador via diretivas de
 *          compilaГЦo e definiГУes (defines).
 * Revision history:
 *      1:  CriaГЦo do arquivo de configuraГЦo.
 *      2:  TraduГЦo dos termos de aceitaГЦo de uso do MPLABX da Microchip;
 *          ComentАrio nas diretivas e definiГУes (defines).
 */

#ifndef CONFIG_H
#define CONFIG_H

#pragma config FOSC  = INTRC_NOCLKOUT   // Fonte de clock: oscilador interno
#pragma config WDTE  = OFF              // Desabilita WatchDog Timer
#pragma config MCLRE = OFF              // Desab. Master Clear via pino
#pragma config LVP   = OFF              // Desab. gravaГЦo em baixa tensЦo

#define _XTAL_FREQ     4000000          // Freq. clock interno: 4MHz(padrЦo)

#endif
